#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="core_db")]
	public partial class CoreDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPUConsumerData(PUConsumerData instance);
    partial void UpdatePUConsumerData(PUConsumerData instance);
    partial void DeletePUConsumerData(PUConsumerData instance);
    partial void InsertPUBrand(PUBrand instance);
    partial void UpdatePUBrand(PUBrand instance);
    partial void DeletePUBrand(PUBrand instance);
    partial void InsertPUClient(PUClient instance);
    partial void UpdatePUClient(PUClient instance);
    partial void DeletePUClient(PUClient instance);
    partial void InsertPUEvent(PUEvent instance);
    partial void UpdatePUEvent(PUEvent instance);
    partial void DeletePUEvent(PUEvent instance);
    partial void InsertPUTour(PUTour instance);
    partial void UpdatePUTour(PUTour instance);
    partial void DeletePUTour(PUTour instance);
    partial void InsertPUProgram(PUProgram instance);
    partial void UpdatePUProgram(PUProgram instance);
    partial void DeletePUProgram(PUProgram instance);
    #endregion
		
		public CoreDBDataContext() : 
				base(global::EmailService.Properties.Settings.Default.core_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CoreDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoreDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoreDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoreDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PUConsumerData> PUConsumerDatas
		{
			get
			{
				return this.GetTable<PUConsumerData>();
			}
		}
		
		public System.Data.Linq.Table<PUBrand> PUBrands
		{
			get
			{
				return this.GetTable<PUBrand>();
			}
		}
		
		public System.Data.Linq.Table<PUClient> PUClients
		{
			get
			{
				return this.GetTable<PUClient>();
			}
		}
		
		public System.Data.Linq.Table<PUEvent> PUEvents
		{
			get
			{
				return this.GetTable<PUEvent>();
			}
		}
		
		public System.Data.Linq.Table<PUTour> PUTours
		{
			get
			{
				return this.GetTable<PUTour>();
			}
		}
		
		public System.Data.Linq.Table<PUProgram> PUPrograms
		{
			get
			{
				return this.GetTable<PUProgram>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PUConsumerData")]
	public partial class PUConsumerData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ConsumerDataID;
		
		private int _EventID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _Phone;
		
		private string _CompressedImageName;
		
		private string _RawImageName;
		
		private string _OverlayImageName;
		
		private System.Nullable<System.DateTime> _PictureTakenDate;
		
		private string _DeviceID;
		
		private bool _OnsiteServerFlag;
		
		private bool _ImageSent;
		
		private bool _ImagesUploaded;
		
		private System.DateTime _LastModifiedDate;
		
		private System.Nullable<int> _MicrositeViews;
		
		private System.Nullable<int> _FacebookUploads;
		
		private int _TwitterClicks;
		
		private int _PhotoPrintClicks;
		
		private int _PhotoSaveClicks;
		
		private int _PhotoWallPaperClicks;
		
		private string _SecureCode;
		
		private int _MicrositeMobilePictureViews;
		
		private string _WebCombinedImageName;
		
		private int _FacebookPictureViews;
		
		private int _FacebookFriends;
		
		private bool _MMSSent;
		
		private bool _SurveyCompleted;
		
		private string _MMSEmail;
		
		private string _AppVersion;
		
		private System.Nullable<bool> _DigitalImagePurchased;
		
		private string _DigitalSignatureImageName;
		
		private EntityRef<PUEvent> _PUEvent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnConsumerDataIDChanging(int value);
    partial void OnConsumerDataIDChanged();
    partial void OnEventIDChanging(int value);
    partial void OnEventIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnCompressedImageNameChanging(string value);
    partial void OnCompressedImageNameChanged();
    partial void OnRawImageNameChanging(string value);
    partial void OnRawImageNameChanged();
    partial void OnOverlayImageNameChanging(string value);
    partial void OnOverlayImageNameChanged();
    partial void OnPictureTakenDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPictureTakenDateChanged();
    partial void OnDeviceIDChanging(string value);
    partial void OnDeviceIDChanged();
    partial void OnOnsiteServerFlagChanging(bool value);
    partial void OnOnsiteServerFlagChanged();
    partial void OnImageSentChanging(bool value);
    partial void OnImageSentChanged();
    partial void OnImagesUploadedChanging(bool value);
    partial void OnImagesUploadedChanged();
    partial void OnLastModifiedDateChanging(System.DateTime value);
    partial void OnLastModifiedDateChanged();
    partial void OnMicrositeViewsChanging(System.Nullable<int> value);
    partial void OnMicrositeViewsChanged();
    partial void OnFacebookUploadsChanging(System.Nullable<int> value);
    partial void OnFacebookUploadsChanged();
    partial void OnTwitterClicksChanging(int value);
    partial void OnTwitterClicksChanged();
    partial void OnPhotoPrintClicksChanging(int value);
    partial void OnPhotoPrintClicksChanged();
    partial void OnPhotoSaveClicksChanging(int value);
    partial void OnPhotoSaveClicksChanged();
    partial void OnPhotoWallPaperClicksChanging(int value);
    partial void OnPhotoWallPaperClicksChanged();
    partial void OnSecureCodeChanging(string value);
    partial void OnSecureCodeChanged();
    partial void OnMicrositeMobilePictureViewsChanging(int value);
    partial void OnMicrositeMobilePictureViewsChanged();
    partial void OnWebCombinedImageNameChanging(string value);
    partial void OnWebCombinedImageNameChanged();
    partial void OnFacebookPictureViewsChanging(int value);
    partial void OnFacebookPictureViewsChanged();
    partial void OnFacebookFriendsChanging(int value);
    partial void OnFacebookFriendsChanged();
    partial void OnMMSSentChanging(bool value);
    partial void OnMMSSentChanged();
    partial void OnSurveyCompletedChanging(bool value);
    partial void OnSurveyCompletedChanged();
    partial void OnMMSEmailChanging(string value);
    partial void OnMMSEmailChanged();
    partial void OnAppVersionChanging(string value);
    partial void OnAppVersionChanged();
    partial void OnDigitalImagePurchasedChanging(System.Nullable<bool> value);
    partial void OnDigitalImagePurchasedChanged();
    partial void OnDigitalSignatureImageNameChanging(string value);
    partial void OnDigitalSignatureImageNameChanged();
    #endregion
		
		public PUConsumerData()
		{
			this._PUEvent = default(EntityRef<PUEvent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumerDataID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ConsumerDataID
		{
			get
			{
				return this._ConsumerDataID;
			}
			set
			{
				if ((this._ConsumerDataID != value))
				{
					this.OnConsumerDataIDChanging(value);
					this.SendPropertyChanging();
					this._ConsumerDataID = value;
					this.SendPropertyChanged("ConsumerDataID");
					this.OnConsumerDataIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventID", DbType="Int NOT NULL")]
		public int EventID
		{
			get
			{
				return this._EventID;
			}
			set
			{
				if ((this._EventID != value))
				{
					if (this._PUEvent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEventIDChanging(value);
					this.SendPropertyChanging();
					this._EventID = value;
					this.SendPropertyChanged("EventID");
					this.OnEventIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompressedImageName", DbType="NVarChar(255)")]
		public string CompressedImageName
		{
			get
			{
				return this._CompressedImageName;
			}
			set
			{
				if ((this._CompressedImageName != value))
				{
					this.OnCompressedImageNameChanging(value);
					this.SendPropertyChanging();
					this._CompressedImageName = value;
					this.SendPropertyChanged("CompressedImageName");
					this.OnCompressedImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawImageName", DbType="NVarChar(255)")]
		public string RawImageName
		{
			get
			{
				return this._RawImageName;
			}
			set
			{
				if ((this._RawImageName != value))
				{
					this.OnRawImageNameChanging(value);
					this.SendPropertyChanging();
					this._RawImageName = value;
					this.SendPropertyChanged("RawImageName");
					this.OnRawImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverlayImageName", DbType="NVarChar(255)")]
		public string OverlayImageName
		{
			get
			{
				return this._OverlayImageName;
			}
			set
			{
				if ((this._OverlayImageName != value))
				{
					this.OnOverlayImageNameChanging(value);
					this.SendPropertyChanging();
					this._OverlayImageName = value;
					this.SendPropertyChanged("OverlayImageName");
					this.OnOverlayImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PictureTakenDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PictureTakenDate
		{
			get
			{
				return this._PictureTakenDate;
			}
			set
			{
				if ((this._PictureTakenDate != value))
				{
					this.OnPictureTakenDateChanging(value);
					this.SendPropertyChanging();
					this._PictureTakenDate = value;
					this.SendPropertyChanged("PictureTakenDate");
					this.OnPictureTakenDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceID", DbType="NVarChar(50)")]
		public string DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				if ((this._DeviceID != value))
				{
					this.OnDeviceIDChanging(value);
					this.SendPropertyChanging();
					this._DeviceID = value;
					this.SendPropertyChanged("DeviceID");
					this.OnDeviceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnsiteServerFlag", DbType="Bit NOT NULL")]
		public bool OnsiteServerFlag
		{
			get
			{
				return this._OnsiteServerFlag;
			}
			set
			{
				if ((this._OnsiteServerFlag != value))
				{
					this.OnOnsiteServerFlagChanging(value);
					this.SendPropertyChanging();
					this._OnsiteServerFlag = value;
					this.SendPropertyChanged("OnsiteServerFlag");
					this.OnOnsiteServerFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageSent", DbType="Bit NOT NULL")]
		public bool ImageSent
		{
			get
			{
				return this._ImageSent;
			}
			set
			{
				if ((this._ImageSent != value))
				{
					this.OnImageSentChanging(value);
					this.SendPropertyChanging();
					this._ImageSent = value;
					this.SendPropertyChanged("ImageSent");
					this.OnImageSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagesUploaded", DbType="Bit NOT NULL")]
		public bool ImagesUploaded
		{
			get
			{
				return this._ImagesUploaded;
			}
			set
			{
				if ((this._ImagesUploaded != value))
				{
					this.OnImagesUploadedChanging(value);
					this.SendPropertyChanging();
					this._ImagesUploaded = value;
					this.SendPropertyChanged("ImagesUploaded");
					this.OnImagesUploadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this.OnLastModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedDate = value;
					this.SendPropertyChanged("LastModifiedDate");
					this.OnLastModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MicrositeViews", DbType="Int")]
		public System.Nullable<int> MicrositeViews
		{
			get
			{
				return this._MicrositeViews;
			}
			set
			{
				if ((this._MicrositeViews != value))
				{
					this.OnMicrositeViewsChanging(value);
					this.SendPropertyChanging();
					this._MicrositeViews = value;
					this.SendPropertyChanged("MicrositeViews");
					this.OnMicrositeViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookUploads", DbType="Int")]
		public System.Nullable<int> FacebookUploads
		{
			get
			{
				return this._FacebookUploads;
			}
			set
			{
				if ((this._FacebookUploads != value))
				{
					this.OnFacebookUploadsChanging(value);
					this.SendPropertyChanging();
					this._FacebookUploads = value;
					this.SendPropertyChanged("FacebookUploads");
					this.OnFacebookUploadsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterClicks", DbType="Int NOT NULL")]
		public int TwitterClicks
		{
			get
			{
				return this._TwitterClicks;
			}
			set
			{
				if ((this._TwitterClicks != value))
				{
					this.OnTwitterClicksChanging(value);
					this.SendPropertyChanging();
					this._TwitterClicks = value;
					this.SendPropertyChanged("TwitterClicks");
					this.OnTwitterClicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoPrintClicks", DbType="Int NOT NULL")]
		public int PhotoPrintClicks
		{
			get
			{
				return this._PhotoPrintClicks;
			}
			set
			{
				if ((this._PhotoPrintClicks != value))
				{
					this.OnPhotoPrintClicksChanging(value);
					this.SendPropertyChanging();
					this._PhotoPrintClicks = value;
					this.SendPropertyChanged("PhotoPrintClicks");
					this.OnPhotoPrintClicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoSaveClicks", DbType="Int NOT NULL")]
		public int PhotoSaveClicks
		{
			get
			{
				return this._PhotoSaveClicks;
			}
			set
			{
				if ((this._PhotoSaveClicks != value))
				{
					this.OnPhotoSaveClicksChanging(value);
					this.SendPropertyChanging();
					this._PhotoSaveClicks = value;
					this.SendPropertyChanged("PhotoSaveClicks");
					this.OnPhotoSaveClicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoWallPaperClicks", DbType="Int NOT NULL")]
		public int PhotoWallPaperClicks
		{
			get
			{
				return this._PhotoWallPaperClicks;
			}
			set
			{
				if ((this._PhotoWallPaperClicks != value))
				{
					this.OnPhotoWallPaperClicksChanging(value);
					this.SendPropertyChanging();
					this._PhotoWallPaperClicks = value;
					this.SendPropertyChanged("PhotoWallPaperClicks");
					this.OnPhotoWallPaperClicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecureCode", DbType="NVarChar(25)")]
		public string SecureCode
		{
			get
			{
				return this._SecureCode;
			}
			set
			{
				if ((this._SecureCode != value))
				{
					this.OnSecureCodeChanging(value);
					this.SendPropertyChanging();
					this._SecureCode = value;
					this.SendPropertyChanged("SecureCode");
					this.OnSecureCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MicrositeMobilePictureViews", DbType="Int NOT NULL")]
		public int MicrositeMobilePictureViews
		{
			get
			{
				return this._MicrositeMobilePictureViews;
			}
			set
			{
				if ((this._MicrositeMobilePictureViews != value))
				{
					this.OnMicrositeMobilePictureViewsChanging(value);
					this.SendPropertyChanging();
					this._MicrositeMobilePictureViews = value;
					this.SendPropertyChanged("MicrositeMobilePictureViews");
					this.OnMicrositeMobilePictureViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebCombinedImageName", DbType="NVarChar(255)")]
		public string WebCombinedImageName
		{
			get
			{
				return this._WebCombinedImageName;
			}
			set
			{
				if ((this._WebCombinedImageName != value))
				{
					this.OnWebCombinedImageNameChanging(value);
					this.SendPropertyChanging();
					this._WebCombinedImageName = value;
					this.SendPropertyChanged("WebCombinedImageName");
					this.OnWebCombinedImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookPictureViews", DbType="Int NOT NULL")]
		public int FacebookPictureViews
		{
			get
			{
				return this._FacebookPictureViews;
			}
			set
			{
				if ((this._FacebookPictureViews != value))
				{
					this.OnFacebookPictureViewsChanging(value);
					this.SendPropertyChanging();
					this._FacebookPictureViews = value;
					this.SendPropertyChanged("FacebookPictureViews");
					this.OnFacebookPictureViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookFriends", DbType="Int NOT NULL")]
		public int FacebookFriends
		{
			get
			{
				return this._FacebookFriends;
			}
			set
			{
				if ((this._FacebookFriends != value))
				{
					this.OnFacebookFriendsChanging(value);
					this.SendPropertyChanging();
					this._FacebookFriends = value;
					this.SendPropertyChanged("FacebookFriends");
					this.OnFacebookFriendsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MMSSent", DbType="Bit NOT NULL")]
		public bool MMSSent
		{
			get
			{
				return this._MMSSent;
			}
			set
			{
				if ((this._MMSSent != value))
				{
					this.OnMMSSentChanging(value);
					this.SendPropertyChanging();
					this._MMSSent = value;
					this.SendPropertyChanged("MMSSent");
					this.OnMMSSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyCompleted", DbType="Bit NOT NULL")]
		public bool SurveyCompleted
		{
			get
			{
				return this._SurveyCompleted;
			}
			set
			{
				if ((this._SurveyCompleted != value))
				{
					this.OnSurveyCompletedChanging(value);
					this.SendPropertyChanging();
					this._SurveyCompleted = value;
					this.SendPropertyChanged("SurveyCompleted");
					this.OnSurveyCompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MMSEmail", DbType="NVarChar(255)")]
		public string MMSEmail
		{
			get
			{
				return this._MMSEmail;
			}
			set
			{
				if ((this._MMSEmail != value))
				{
					this.OnMMSEmailChanging(value);
					this.SendPropertyChanging();
					this._MMSEmail = value;
					this.SendPropertyChanged("MMSEmail");
					this.OnMMSEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppVersion", DbType="NVarChar(20)")]
		public string AppVersion
		{
			get
			{
				return this._AppVersion;
			}
			set
			{
				if ((this._AppVersion != value))
				{
					this.OnAppVersionChanging(value);
					this.SendPropertyChanging();
					this._AppVersion = value;
					this.SendPropertyChanged("AppVersion");
					this.OnAppVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DigitalImagePurchased", DbType="Bit")]
		public System.Nullable<bool> DigitalImagePurchased
		{
			get
			{
				return this._DigitalImagePurchased;
			}
			set
			{
				if ((this._DigitalImagePurchased != value))
				{
					this.OnDigitalImagePurchasedChanging(value);
					this.SendPropertyChanging();
					this._DigitalImagePurchased = value;
					this.SendPropertyChanged("DigitalImagePurchased");
					this.OnDigitalImagePurchasedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DigitalSignatureImageName", DbType="NVarChar(255)")]
		public string DigitalSignatureImageName
		{
			get
			{
				return this._DigitalSignatureImageName;
			}
			set
			{
				if ((this._DigitalSignatureImageName != value))
				{
					this.OnDigitalSignatureImageNameChanging(value);
					this.SendPropertyChanging();
					this._DigitalSignatureImageName = value;
					this.SendPropertyChanged("DigitalSignatureImageName");
					this.OnDigitalSignatureImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PUEvent_PUConsumerData", Storage="_PUEvent", ThisKey="EventID", OtherKey="EventID", IsForeignKey=true)]
		public PUEvent PUEvent
		{
			get
			{
				return this._PUEvent.Entity;
			}
			set
			{
				PUEvent previousValue = this._PUEvent.Entity;
				if (((previousValue != value) 
							|| (this._PUEvent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PUEvent.Entity = null;
						previousValue.PUConsumerDatas.Remove(this);
					}
					this._PUEvent.Entity = value;
					if ((value != null))
					{
						value.PUConsumerDatas.Add(this);
						this._EventID = value.EventID;
					}
					else
					{
						this._EventID = default(int);
					}
					this.SendPropertyChanged("PUEvent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PUBrands")]
	public partial class PUBrand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BrandID;
		
		private int _ClientID;
		
		private string _Name;
		
		private string _SmallLogoName;
		
		private string _Color;
		
		private string _LogoLinkURL;
		
		private EntitySet<PUProgram> _PUPrograms;
		
		private EntityRef<PUClient> _PUClient;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBrandIDChanging(int value);
    partial void OnBrandIDChanged();
    partial void OnClientIDChanging(int value);
    partial void OnClientIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSmallLogoNameChanging(string value);
    partial void OnSmallLogoNameChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnLogoLinkURLChanging(string value);
    partial void OnLogoLinkURLChanged();
    #endregion
		
		public PUBrand()
		{
			this._PUPrograms = new EntitySet<PUProgram>(new Action<PUProgram>(this.attach_PUPrograms), new Action<PUProgram>(this.detach_PUPrograms));
			this._PUClient = default(EntityRef<PUClient>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BrandID
		{
			get
			{
				return this._BrandID;
			}
			set
			{
				if ((this._BrandID != value))
				{
					this.OnBrandIDChanging(value);
					this.SendPropertyChanging();
					this._BrandID = value;
					this.SendPropertyChanged("BrandID");
					this.OnBrandIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="Int NOT NULL")]
		public int ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					if (this._PUClient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallLogoName", DbType="NVarChar(255)")]
		public string SmallLogoName
		{
			get
			{
				return this._SmallLogoName;
			}
			set
			{
				if ((this._SmallLogoName != value))
				{
					this.OnSmallLogoNameChanging(value);
					this.SendPropertyChanging();
					this._SmallLogoName = value;
					this.SendPropertyChanged("SmallLogoName");
					this.OnSmallLogoNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoLinkURL", DbType="NVarChar(255)")]
		public string LogoLinkURL
		{
			get
			{
				return this._LogoLinkURL;
			}
			set
			{
				if ((this._LogoLinkURL != value))
				{
					this.OnLogoLinkURLChanging(value);
					this.SendPropertyChanging();
					this._LogoLinkURL = value;
					this.SendPropertyChanged("LogoLinkURL");
					this.OnLogoLinkURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PUBrand_PUProgram", Storage="_PUPrograms", ThisKey="BrandID", OtherKey="BrandID")]
		public EntitySet<PUProgram> PUPrograms
		{
			get
			{
				return this._PUPrograms;
			}
			set
			{
				this._PUPrograms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PUClient_PUBrand", Storage="_PUClient", ThisKey="ClientID", OtherKey="ClientID", IsForeignKey=true)]
		public PUClient PUClient
		{
			get
			{
				return this._PUClient.Entity;
			}
			set
			{
				PUClient previousValue = this._PUClient.Entity;
				if (((previousValue != value) 
							|| (this._PUClient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PUClient.Entity = null;
						previousValue.PUBrands.Remove(this);
					}
					this._PUClient.Entity = value;
					if ((value != null))
					{
						value.PUBrands.Add(this);
						this._ClientID = value.ClientID;
					}
					else
					{
						this._ClientID = default(int);
					}
					this.SendPropertyChanged("PUClient");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PUPrograms(PUProgram entity)
		{
			this.SendPropertyChanging();
			entity.PUBrand = this;
		}
		
		private void detach_PUPrograms(PUProgram entity)
		{
			this.SendPropertyChanging();
			entity.PUBrand = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PUClients")]
	public partial class PUClient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ClientID;
		
		private string _Name;
		
		private EntitySet<PUBrand> _PUBrands;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClientIDChanging(int value);
    partial void OnClientIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public PUClient()
		{
			this._PUBrands = new EntitySet<PUBrand>(new Action<PUBrand>(this.attach_PUBrands), new Action<PUBrand>(this.detach_PUBrands));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PUClient_PUBrand", Storage="_PUBrands", ThisKey="ClientID", OtherKey="ClientID")]
		public EntitySet<PUBrand> PUBrands
		{
			get
			{
				return this._PUBrands;
			}
			set
			{
				this._PUBrands.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PUBrands(PUBrand entity)
		{
			this.SendPropertyChanging();
			entity.PUClient = this;
		}
		
		private void detach_PUBrands(PUBrand entity)
		{
			this.SendPropertyChanging();
			entity.PUClient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PUEvents")]
	public partial class PUEvent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EventID;
		
		private int _TourID;
		
		private System.Nullable<int> _EventManagerID;
		
		private string _Name;
		
		private string _City;
		
		private string _Region;
		
		private System.DateTime _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _OptInText;
		
		private bool _SaveRawImage;
		
		private bool _PhoneRequired;
		
		private bool _EmailRequired;
		
		private bool _FirstNameRequired;
		
		private bool _LastNameRequired;
		
		private string _EmailSubject;
		
		private string _EmailBody;
		
		private string _BasicSurveyDisplayFlags;
		
		private string _BasicSurveyRequiredFlags;
		
		private string _EmailFrom;
		
		private System.Nullable<bool> _SendLink;
		
		private System.Nullable<bool> _ShowEmail;
		
		private System.Nullable<bool> _ShowPhone;
		
		private System.Nullable<bool> _ShowFirstName;
		
		private System.Nullable<bool> _ShowLastName;
		
		private string _AdvancedSurveyDisplayFlags;
		
		private string _AdvancedSurveyRequiredFlags;
		
		private string _AdvancedSurveyQuestions;
		
		private string _FlexDD1Answers;
		
		private string _FlexDD2Answers;
		
		private string _FlexDD3Answers;
		
		private string _ReleaseText;
		
		private string _TextSubject;
		
		private string _TextBody;
		
		private string _EmailHost;
		
		private string _EmailPort;
		
		private string _EmailUserID;
		
		private string _EmailPassword;
		
		private bool _AttachImages;
		
		private string _PhotoViewerBackground;
		
		private string _PhotoViewerContent;
		
		private string _PhotoViewerFrame;
		
		private bool _ShowSecureCode;
		
		private bool _SecureCodeRequired;
		
		private int _ImageSearchVisits;
		
		private int _SecureCodesSearched;
		
		private string _BatchCode;
		
		private string _EventTrackingCode;
		
		private System.Nullable<bool> _ShowWebOverlayScrollingModule;
		
		private System.Nullable<bool> _ShowFacebookLoginOption;
		
		private int _FacebookGalleryViews;
		
		private bool _SelfGuidedProcess;
		
		private bool _FacebookWebViewMode;
		
		private bool _ShowLandscapeDisplay;
		
		private int _FacebookImageSearchVisits;
		
		private bool _SendEmail;
		
		private bool _SendMMS;
		
		private int _SendMMSOption_CodeID;
		
		private bool _HasWebSurvey;
		
		private int _EventType_CodeID;
		
		private string _FacebookCaption;
		
		private string _TwitterCaption;
		
		private int _PrintOption;
		
		private EntitySet<PUConsumerData> _PUConsumerDatas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEventIDChanging(int value);
    partial void OnEventIDChanged();
    partial void OnTourIDChanging(int value);
    partial void OnTourIDChanged();
    partial void OnEventManagerIDChanging(System.Nullable<int> value);
    partial void OnEventManagerIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnOptInTextChanging(string value);
    partial void OnOptInTextChanged();
    partial void OnSaveRawImageChanging(bool value);
    partial void OnSaveRawImageChanged();
    partial void OnPhoneRequiredChanging(bool value);
    partial void OnPhoneRequiredChanged();
    partial void OnEmailRequiredChanging(bool value);
    partial void OnEmailRequiredChanged();
    partial void OnFirstNameRequiredChanging(bool value);
    partial void OnFirstNameRequiredChanged();
    partial void OnLastNameRequiredChanging(bool value);
    partial void OnLastNameRequiredChanged();
    partial void OnEmailSubjectChanging(string value);
    partial void OnEmailSubjectChanged();
    partial void OnEmailBodyChanging(string value);
    partial void OnEmailBodyChanged();
    partial void OnBasicSurveyDisplayFlagsChanging(string value);
    partial void OnBasicSurveyDisplayFlagsChanged();
    partial void OnBasicSurveyRequiredFlagsChanging(string value);
    partial void OnBasicSurveyRequiredFlagsChanged();
    partial void OnEmailFromChanging(string value);
    partial void OnEmailFromChanged();
    partial void OnSendLinkChanging(System.Nullable<bool> value);
    partial void OnSendLinkChanged();
    partial void OnShowEmailChanging(System.Nullable<bool> value);
    partial void OnShowEmailChanged();
    partial void OnShowPhoneChanging(System.Nullable<bool> value);
    partial void OnShowPhoneChanged();
    partial void OnShowFirstNameChanging(System.Nullable<bool> value);
    partial void OnShowFirstNameChanged();
    partial void OnShowLastNameChanging(System.Nullable<bool> value);
    partial void OnShowLastNameChanged();
    partial void OnAdvancedSurveyDisplayFlagsChanging(string value);
    partial void OnAdvancedSurveyDisplayFlagsChanged();
    partial void OnAdvancedSurveyRequiredFlagsChanging(string value);
    partial void OnAdvancedSurveyRequiredFlagsChanged();
    partial void OnAdvancedSurveyQuestionsChanging(string value);
    partial void OnAdvancedSurveyQuestionsChanged();
    partial void OnFlexDD1AnswersChanging(string value);
    partial void OnFlexDD1AnswersChanged();
    partial void OnFlexDD2AnswersChanging(string value);
    partial void OnFlexDD2AnswersChanged();
    partial void OnFlexDD3AnswersChanging(string value);
    partial void OnFlexDD3AnswersChanged();
    partial void OnReleaseTextChanging(string value);
    partial void OnReleaseTextChanged();
    partial void OnTextSubjectChanging(string value);
    partial void OnTextSubjectChanged();
    partial void OnTextBodyChanging(string value);
    partial void OnTextBodyChanged();
    partial void OnEmailHostChanging(string value);
    partial void OnEmailHostChanged();
    partial void OnEmailPortChanging(string value);
    partial void OnEmailPortChanged();
    partial void OnEmailUserIDChanging(string value);
    partial void OnEmailUserIDChanged();
    partial void OnEmailPasswordChanging(string value);
    partial void OnEmailPasswordChanged();
    partial void OnAttachImagesChanging(bool value);
    partial void OnAttachImagesChanged();
    partial void OnPhotoViewerBackgroundChanging(string value);
    partial void OnPhotoViewerBackgroundChanged();
    partial void OnPhotoViewerContentChanging(string value);
    partial void OnPhotoViewerContentChanged();
    partial void OnPhotoViewerFrameChanging(string value);
    partial void OnPhotoViewerFrameChanged();
    partial void OnShowSecureCodeChanging(bool value);
    partial void OnShowSecureCodeChanged();
    partial void OnSecureCodeRequiredChanging(bool value);
    partial void OnSecureCodeRequiredChanged();
    partial void OnImageSearchVisitsChanging(int value);
    partial void OnImageSearchVisitsChanged();
    partial void OnSecureCodesSearchedChanging(int value);
    partial void OnSecureCodesSearchedChanged();
    partial void OnBatchCodeChanging(string value);
    partial void OnBatchCodeChanged();
    partial void OnEventTrackingCodeChanging(string value);
    partial void OnEventTrackingCodeChanged();
    partial void OnShowWebOverlayScrollingModuleChanging(System.Nullable<bool> value);
    partial void OnShowWebOverlayScrollingModuleChanged();
    partial void OnShowFacebookLoginOptionChanging(System.Nullable<bool> value);
    partial void OnShowFacebookLoginOptionChanged();
    partial void OnFacebookGalleryViewsChanging(int value);
    partial void OnFacebookGalleryViewsChanged();
    partial void OnSelfGuidedProcessChanging(bool value);
    partial void OnSelfGuidedProcessChanged();
    partial void OnFacebookWebViewModeChanging(bool value);
    partial void OnFacebookWebViewModeChanged();
    partial void OnShowLandscapeDisplayChanging(bool value);
    partial void OnShowLandscapeDisplayChanged();
    partial void OnFacebookImageSearchVisitsChanging(int value);
    partial void OnFacebookImageSearchVisitsChanged();
    partial void OnSendEmailChanging(bool value);
    partial void OnSendEmailChanged();
    partial void OnSendMMSChanging(bool value);
    partial void OnSendMMSChanged();
    partial void OnSendMMSOption_CodeIDChanging(int value);
    partial void OnSendMMSOption_CodeIDChanged();
    partial void OnHasWebSurveyChanging(bool value);
    partial void OnHasWebSurveyChanged();
    partial void OnEventType_CodeIDChanging(int value);
    partial void OnEventType_CodeIDChanged();
    partial void OnFacebookCaptionChanging(string value);
    partial void OnFacebookCaptionChanged();
    partial void OnTwitterCaptionChanging(string value);
    partial void OnTwitterCaptionChanged();
    partial void OnPrintOptionChanging(int value);
    partial void OnPrintOptionChanged();
    #endregion
		
		public PUEvent()
		{
			this._PUConsumerDatas = new EntitySet<PUConsumerData>(new Action<PUConsumerData>(this.attach_PUConsumerDatas), new Action<PUConsumerData>(this.detach_PUConsumerDatas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EventID
		{
			get
			{
				return this._EventID;
			}
			set
			{
				if ((this._EventID != value))
				{
					this.OnEventIDChanging(value);
					this.SendPropertyChanging();
					this._EventID = value;
					this.SendPropertyChanged("EventID");
					this.OnEventIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TourID", DbType="Int NOT NULL")]
		public int TourID
		{
			get
			{
				return this._TourID;
			}
			set
			{
				if ((this._TourID != value))
				{
					this.OnTourIDChanging(value);
					this.SendPropertyChanging();
					this._TourID = value;
					this.SendPropertyChanged("TourID");
					this.OnTourIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventManagerID", DbType="Int")]
		public System.Nullable<int> EventManagerID
		{
			get
			{
				return this._EventManagerID;
			}
			set
			{
				if ((this._EventManagerID != value))
				{
					this.OnEventManagerIDChanging(value);
					this.SendPropertyChanging();
					this._EventManagerID = value;
					this.SendPropertyChanged("EventManagerID");
					this.OnEventManagerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(255)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(10)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptInText", DbType="NVarChar(2000)")]
		public string OptInText
		{
			get
			{
				return this._OptInText;
			}
			set
			{
				if ((this._OptInText != value))
				{
					this.OnOptInTextChanging(value);
					this.SendPropertyChanging();
					this._OptInText = value;
					this.SendPropertyChanged("OptInText");
					this.OnOptInTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveRawImage", DbType="Bit NOT NULL")]
		public bool SaveRawImage
		{
			get
			{
				return this._SaveRawImage;
			}
			set
			{
				if ((this._SaveRawImage != value))
				{
					this.OnSaveRawImageChanging(value);
					this.SendPropertyChanging();
					this._SaveRawImage = value;
					this.SendPropertyChanged("SaveRawImage");
					this.OnSaveRawImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneRequired", DbType="Bit NOT NULL")]
		public bool PhoneRequired
		{
			get
			{
				return this._PhoneRequired;
			}
			set
			{
				if ((this._PhoneRequired != value))
				{
					this.OnPhoneRequiredChanging(value);
					this.SendPropertyChanging();
					this._PhoneRequired = value;
					this.SendPropertyChanged("PhoneRequired");
					this.OnPhoneRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailRequired", DbType="Bit NOT NULL")]
		public bool EmailRequired
		{
			get
			{
				return this._EmailRequired;
			}
			set
			{
				if ((this._EmailRequired != value))
				{
					this.OnEmailRequiredChanging(value);
					this.SendPropertyChanging();
					this._EmailRequired = value;
					this.SendPropertyChanged("EmailRequired");
					this.OnEmailRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstNameRequired", DbType="Bit NOT NULL")]
		public bool FirstNameRequired
		{
			get
			{
				return this._FirstNameRequired;
			}
			set
			{
				if ((this._FirstNameRequired != value))
				{
					this.OnFirstNameRequiredChanging(value);
					this.SendPropertyChanging();
					this._FirstNameRequired = value;
					this.SendPropertyChanged("FirstNameRequired");
					this.OnFirstNameRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastNameRequired", DbType="Bit NOT NULL")]
		public bool LastNameRequired
		{
			get
			{
				return this._LastNameRequired;
			}
			set
			{
				if ((this._LastNameRequired != value))
				{
					this.OnLastNameRequiredChanging(value);
					this.SendPropertyChanging();
					this._LastNameRequired = value;
					this.SendPropertyChanged("LastNameRequired");
					this.OnLastNameRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="NVarChar(255)")]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this.OnEmailSubjectChanging(value);
					this.SendPropertyChanging();
					this._EmailSubject = value;
					this.SendPropertyChanged("EmailSubject");
					this.OnEmailSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBody", DbType="NVarChar(4000)")]
		public string EmailBody
		{
			get
			{
				return this._EmailBody;
			}
			set
			{
				if ((this._EmailBody != value))
				{
					this.OnEmailBodyChanging(value);
					this.SendPropertyChanging();
					this._EmailBody = value;
					this.SendPropertyChanged("EmailBody");
					this.OnEmailBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSurveyDisplayFlags", DbType="NVarChar(255)")]
		public string BasicSurveyDisplayFlags
		{
			get
			{
				return this._BasicSurveyDisplayFlags;
			}
			set
			{
				if ((this._BasicSurveyDisplayFlags != value))
				{
					this.OnBasicSurveyDisplayFlagsChanging(value);
					this.SendPropertyChanging();
					this._BasicSurveyDisplayFlags = value;
					this.SendPropertyChanged("BasicSurveyDisplayFlags");
					this.OnBasicSurveyDisplayFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSurveyRequiredFlags", DbType="NVarChar(255)")]
		public string BasicSurveyRequiredFlags
		{
			get
			{
				return this._BasicSurveyRequiredFlags;
			}
			set
			{
				if ((this._BasicSurveyRequiredFlags != value))
				{
					this.OnBasicSurveyRequiredFlagsChanging(value);
					this.SendPropertyChanging();
					this._BasicSurveyRequiredFlags = value;
					this.SendPropertyChanged("BasicSurveyRequiredFlags");
					this.OnBasicSurveyRequiredFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailFrom", DbType="NVarChar(255)")]
		public string EmailFrom
		{
			get
			{
				return this._EmailFrom;
			}
			set
			{
				if ((this._EmailFrom != value))
				{
					this.OnEmailFromChanging(value);
					this.SendPropertyChanging();
					this._EmailFrom = value;
					this.SendPropertyChanged("EmailFrom");
					this.OnEmailFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendLink", DbType="Bit")]
		public System.Nullable<bool> SendLink
		{
			get
			{
				return this._SendLink;
			}
			set
			{
				if ((this._SendLink != value))
				{
					this.OnSendLinkChanging(value);
					this.SendPropertyChanging();
					this._SendLink = value;
					this.SendPropertyChanged("SendLink");
					this.OnSendLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowEmail", DbType="Bit")]
		public System.Nullable<bool> ShowEmail
		{
			get
			{
				return this._ShowEmail;
			}
			set
			{
				if ((this._ShowEmail != value))
				{
					this.OnShowEmailChanging(value);
					this.SendPropertyChanging();
					this._ShowEmail = value;
					this.SendPropertyChanged("ShowEmail");
					this.OnShowEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowPhone", DbType="Bit")]
		public System.Nullable<bool> ShowPhone
		{
			get
			{
				return this._ShowPhone;
			}
			set
			{
				if ((this._ShowPhone != value))
				{
					this.OnShowPhoneChanging(value);
					this.SendPropertyChanging();
					this._ShowPhone = value;
					this.SendPropertyChanged("ShowPhone");
					this.OnShowPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowFirstName", DbType="Bit")]
		public System.Nullable<bool> ShowFirstName
		{
			get
			{
				return this._ShowFirstName;
			}
			set
			{
				if ((this._ShowFirstName != value))
				{
					this.OnShowFirstNameChanging(value);
					this.SendPropertyChanging();
					this._ShowFirstName = value;
					this.SendPropertyChanged("ShowFirstName");
					this.OnShowFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowLastName", DbType="Bit")]
		public System.Nullable<bool> ShowLastName
		{
			get
			{
				return this._ShowLastName;
			}
			set
			{
				if ((this._ShowLastName != value))
				{
					this.OnShowLastNameChanging(value);
					this.SendPropertyChanging();
					this._ShowLastName = value;
					this.SendPropertyChanged("ShowLastName");
					this.OnShowLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvancedSurveyDisplayFlags", DbType="NVarChar(255)")]
		public string AdvancedSurveyDisplayFlags
		{
			get
			{
				return this._AdvancedSurveyDisplayFlags;
			}
			set
			{
				if ((this._AdvancedSurveyDisplayFlags != value))
				{
					this.OnAdvancedSurveyDisplayFlagsChanging(value);
					this.SendPropertyChanging();
					this._AdvancedSurveyDisplayFlags = value;
					this.SendPropertyChanged("AdvancedSurveyDisplayFlags");
					this.OnAdvancedSurveyDisplayFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvancedSurveyRequiredFlags", DbType="NVarChar(255)")]
		public string AdvancedSurveyRequiredFlags
		{
			get
			{
				return this._AdvancedSurveyRequiredFlags;
			}
			set
			{
				if ((this._AdvancedSurveyRequiredFlags != value))
				{
					this.OnAdvancedSurveyRequiredFlagsChanging(value);
					this.SendPropertyChanging();
					this._AdvancedSurveyRequiredFlags = value;
					this.SendPropertyChanged("AdvancedSurveyRequiredFlags");
					this.OnAdvancedSurveyRequiredFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvancedSurveyQuestions", DbType="NVarChar(500)")]
		public string AdvancedSurveyQuestions
		{
			get
			{
				return this._AdvancedSurveyQuestions;
			}
			set
			{
				if ((this._AdvancedSurveyQuestions != value))
				{
					this.OnAdvancedSurveyQuestionsChanging(value);
					this.SendPropertyChanging();
					this._AdvancedSurveyQuestions = value;
					this.SendPropertyChanged("AdvancedSurveyQuestions");
					this.OnAdvancedSurveyQuestionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlexDD1Answers", DbType="NVarChar(500)")]
		public string FlexDD1Answers
		{
			get
			{
				return this._FlexDD1Answers;
			}
			set
			{
				if ((this._FlexDD1Answers != value))
				{
					this.OnFlexDD1AnswersChanging(value);
					this.SendPropertyChanging();
					this._FlexDD1Answers = value;
					this.SendPropertyChanged("FlexDD1Answers");
					this.OnFlexDD1AnswersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlexDD2Answers", DbType="NVarChar(500)")]
		public string FlexDD2Answers
		{
			get
			{
				return this._FlexDD2Answers;
			}
			set
			{
				if ((this._FlexDD2Answers != value))
				{
					this.OnFlexDD2AnswersChanging(value);
					this.SendPropertyChanging();
					this._FlexDD2Answers = value;
					this.SendPropertyChanged("FlexDD2Answers");
					this.OnFlexDD2AnswersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlexDD3Answers", DbType="NVarChar(500)")]
		public string FlexDD3Answers
		{
			get
			{
				return this._FlexDD3Answers;
			}
			set
			{
				if ((this._FlexDD3Answers != value))
				{
					this.OnFlexDD3AnswersChanging(value);
					this.SendPropertyChanging();
					this._FlexDD3Answers = value;
					this.SendPropertyChanged("FlexDD3Answers");
					this.OnFlexDD3AnswersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseText", DbType="NVarChar(1000)")]
		public string ReleaseText
		{
			get
			{
				return this._ReleaseText;
			}
			set
			{
				if ((this._ReleaseText != value))
				{
					this.OnReleaseTextChanging(value);
					this.SendPropertyChanging();
					this._ReleaseText = value;
					this.SendPropertyChanged("ReleaseText");
					this.OnReleaseTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextSubject", DbType="NVarChar(255)")]
		public string TextSubject
		{
			get
			{
				return this._TextSubject;
			}
			set
			{
				if ((this._TextSubject != value))
				{
					this.OnTextSubjectChanging(value);
					this.SendPropertyChanging();
					this._TextSubject = value;
					this.SendPropertyChanged("TextSubject");
					this.OnTextSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextBody", DbType="NVarChar(255)")]
		public string TextBody
		{
			get
			{
				return this._TextBody;
			}
			set
			{
				if ((this._TextBody != value))
				{
					this.OnTextBodyChanging(value);
					this.SendPropertyChanging();
					this._TextBody = value;
					this.SendPropertyChanged("TextBody");
					this.OnTextBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailHost", DbType="NVarChar(255)")]
		public string EmailHost
		{
			get
			{
				return this._EmailHost;
			}
			set
			{
				if ((this._EmailHost != value))
				{
					this.OnEmailHostChanging(value);
					this.SendPropertyChanging();
					this._EmailHost = value;
					this.SendPropertyChanged("EmailHost");
					this.OnEmailHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailPort", DbType="NVarChar(50)")]
		public string EmailPort
		{
			get
			{
				return this._EmailPort;
			}
			set
			{
				if ((this._EmailPort != value))
				{
					this.OnEmailPortChanging(value);
					this.SendPropertyChanging();
					this._EmailPort = value;
					this.SendPropertyChanged("EmailPort");
					this.OnEmailPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUserID", DbType="NVarChar(255)")]
		public string EmailUserID
		{
			get
			{
				return this._EmailUserID;
			}
			set
			{
				if ((this._EmailUserID != value))
				{
					this.OnEmailUserIDChanging(value);
					this.SendPropertyChanging();
					this._EmailUserID = value;
					this.SendPropertyChanged("EmailUserID");
					this.OnEmailUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailPassword", DbType="NVarChar(50)")]
		public string EmailPassword
		{
			get
			{
				return this._EmailPassword;
			}
			set
			{
				if ((this._EmailPassword != value))
				{
					this.OnEmailPasswordChanging(value);
					this.SendPropertyChanging();
					this._EmailPassword = value;
					this.SendPropertyChanged("EmailPassword");
					this.OnEmailPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachImages", DbType="Bit NOT NULL")]
		public bool AttachImages
		{
			get
			{
				return this._AttachImages;
			}
			set
			{
				if ((this._AttachImages != value))
				{
					this.OnAttachImagesChanging(value);
					this.SendPropertyChanging();
					this._AttachImages = value;
					this.SendPropertyChanged("AttachImages");
					this.OnAttachImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoViewerBackground", DbType="NVarChar(255)")]
		public string PhotoViewerBackground
		{
			get
			{
				return this._PhotoViewerBackground;
			}
			set
			{
				if ((this._PhotoViewerBackground != value))
				{
					this.OnPhotoViewerBackgroundChanging(value);
					this.SendPropertyChanging();
					this._PhotoViewerBackground = value;
					this.SendPropertyChanged("PhotoViewerBackground");
					this.OnPhotoViewerBackgroundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoViewerContent", DbType="NVarChar(255)")]
		public string PhotoViewerContent
		{
			get
			{
				return this._PhotoViewerContent;
			}
			set
			{
				if ((this._PhotoViewerContent != value))
				{
					this.OnPhotoViewerContentChanging(value);
					this.SendPropertyChanging();
					this._PhotoViewerContent = value;
					this.SendPropertyChanged("PhotoViewerContent");
					this.OnPhotoViewerContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoViewerFrame", DbType="NVarChar(255)")]
		public string PhotoViewerFrame
		{
			get
			{
				return this._PhotoViewerFrame;
			}
			set
			{
				if ((this._PhotoViewerFrame != value))
				{
					this.OnPhotoViewerFrameChanging(value);
					this.SendPropertyChanging();
					this._PhotoViewerFrame = value;
					this.SendPropertyChanged("PhotoViewerFrame");
					this.OnPhotoViewerFrameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowSecureCode", DbType="Bit NOT NULL")]
		public bool ShowSecureCode
		{
			get
			{
				return this._ShowSecureCode;
			}
			set
			{
				if ((this._ShowSecureCode != value))
				{
					this.OnShowSecureCodeChanging(value);
					this.SendPropertyChanging();
					this._ShowSecureCode = value;
					this.SendPropertyChanged("ShowSecureCode");
					this.OnShowSecureCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecureCodeRequired", DbType="Bit NOT NULL")]
		public bool SecureCodeRequired
		{
			get
			{
				return this._SecureCodeRequired;
			}
			set
			{
				if ((this._SecureCodeRequired != value))
				{
					this.OnSecureCodeRequiredChanging(value);
					this.SendPropertyChanging();
					this._SecureCodeRequired = value;
					this.SendPropertyChanged("SecureCodeRequired");
					this.OnSecureCodeRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageSearchVisits", DbType="Int NOT NULL")]
		public int ImageSearchVisits
		{
			get
			{
				return this._ImageSearchVisits;
			}
			set
			{
				if ((this._ImageSearchVisits != value))
				{
					this.OnImageSearchVisitsChanging(value);
					this.SendPropertyChanging();
					this._ImageSearchVisits = value;
					this.SendPropertyChanged("ImageSearchVisits");
					this.OnImageSearchVisitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecureCodesSearched", DbType="Int NOT NULL")]
		public int SecureCodesSearched
		{
			get
			{
				return this._SecureCodesSearched;
			}
			set
			{
				if ((this._SecureCodesSearched != value))
				{
					this.OnSecureCodesSearchedChanging(value);
					this.SendPropertyChanging();
					this._SecureCodesSearched = value;
					this.SendPropertyChanged("SecureCodesSearched");
					this.OnSecureCodesSearchedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchCode", DbType="NVarChar(50)")]
		public string BatchCode
		{
			get
			{
				return this._BatchCode;
			}
			set
			{
				if ((this._BatchCode != value))
				{
					this.OnBatchCodeChanging(value);
					this.SendPropertyChanging();
					this._BatchCode = value;
					this.SendPropertyChanged("BatchCode");
					this.OnBatchCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTrackingCode", DbType="NVarChar(50)")]
		public string EventTrackingCode
		{
			get
			{
				return this._EventTrackingCode;
			}
			set
			{
				if ((this._EventTrackingCode != value))
				{
					this.OnEventTrackingCodeChanging(value);
					this.SendPropertyChanging();
					this._EventTrackingCode = value;
					this.SendPropertyChanged("EventTrackingCode");
					this.OnEventTrackingCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowWebOverlayScrollingModule", DbType="Bit")]
		public System.Nullable<bool> ShowWebOverlayScrollingModule
		{
			get
			{
				return this._ShowWebOverlayScrollingModule;
			}
			set
			{
				if ((this._ShowWebOverlayScrollingModule != value))
				{
					this.OnShowWebOverlayScrollingModuleChanging(value);
					this.SendPropertyChanging();
					this._ShowWebOverlayScrollingModule = value;
					this.SendPropertyChanged("ShowWebOverlayScrollingModule");
					this.OnShowWebOverlayScrollingModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowFacebookLoginOption", DbType="Bit")]
		public System.Nullable<bool> ShowFacebookLoginOption
		{
			get
			{
				return this._ShowFacebookLoginOption;
			}
			set
			{
				if ((this._ShowFacebookLoginOption != value))
				{
					this.OnShowFacebookLoginOptionChanging(value);
					this.SendPropertyChanging();
					this._ShowFacebookLoginOption = value;
					this.SendPropertyChanged("ShowFacebookLoginOption");
					this.OnShowFacebookLoginOptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookGalleryViews", DbType="Int NOT NULL")]
		public int FacebookGalleryViews
		{
			get
			{
				return this._FacebookGalleryViews;
			}
			set
			{
				if ((this._FacebookGalleryViews != value))
				{
					this.OnFacebookGalleryViewsChanging(value);
					this.SendPropertyChanging();
					this._FacebookGalleryViews = value;
					this.SendPropertyChanged("FacebookGalleryViews");
					this.OnFacebookGalleryViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelfGuidedProcess", DbType="Bit NOT NULL")]
		public bool SelfGuidedProcess
		{
			get
			{
				return this._SelfGuidedProcess;
			}
			set
			{
				if ((this._SelfGuidedProcess != value))
				{
					this.OnSelfGuidedProcessChanging(value);
					this.SendPropertyChanging();
					this._SelfGuidedProcess = value;
					this.SendPropertyChanged("SelfGuidedProcess");
					this.OnSelfGuidedProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookWebViewMode", DbType="Bit NOT NULL")]
		public bool FacebookWebViewMode
		{
			get
			{
				return this._FacebookWebViewMode;
			}
			set
			{
				if ((this._FacebookWebViewMode != value))
				{
					this.OnFacebookWebViewModeChanging(value);
					this.SendPropertyChanging();
					this._FacebookWebViewMode = value;
					this.SendPropertyChanged("FacebookWebViewMode");
					this.OnFacebookWebViewModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowLandscapeDisplay", DbType="Bit NOT NULL")]
		public bool ShowLandscapeDisplay
		{
			get
			{
				return this._ShowLandscapeDisplay;
			}
			set
			{
				if ((this._ShowLandscapeDisplay != value))
				{
					this.OnShowLandscapeDisplayChanging(value);
					this.SendPropertyChanging();
					this._ShowLandscapeDisplay = value;
					this.SendPropertyChanged("ShowLandscapeDisplay");
					this.OnShowLandscapeDisplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookImageSearchVisits", DbType="Int NOT NULL")]
		public int FacebookImageSearchVisits
		{
			get
			{
				return this._FacebookImageSearchVisits;
			}
			set
			{
				if ((this._FacebookImageSearchVisits != value))
				{
					this.OnFacebookImageSearchVisitsChanging(value);
					this.SendPropertyChanging();
					this._FacebookImageSearchVisits = value;
					this.SendPropertyChanged("FacebookImageSearchVisits");
					this.OnFacebookImageSearchVisitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendEmail", DbType="Bit NOT NULL")]
		public bool SendEmail
		{
			get
			{
				return this._SendEmail;
			}
			set
			{
				if ((this._SendEmail != value))
				{
					this.OnSendEmailChanging(value);
					this.SendPropertyChanging();
					this._SendEmail = value;
					this.SendPropertyChanged("SendEmail");
					this.OnSendEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendMMS", DbType="Bit NOT NULL")]
		public bool SendMMS
		{
			get
			{
				return this._SendMMS;
			}
			set
			{
				if ((this._SendMMS != value))
				{
					this.OnSendMMSChanging(value);
					this.SendPropertyChanging();
					this._SendMMS = value;
					this.SendPropertyChanged("SendMMS");
					this.OnSendMMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendMMSOption_CodeID", DbType="Int NOT NULL")]
		public int SendMMSOption_CodeID
		{
			get
			{
				return this._SendMMSOption_CodeID;
			}
			set
			{
				if ((this._SendMMSOption_CodeID != value))
				{
					this.OnSendMMSOption_CodeIDChanging(value);
					this.SendPropertyChanging();
					this._SendMMSOption_CodeID = value;
					this.SendPropertyChanged("SendMMSOption_CodeID");
					this.OnSendMMSOption_CodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasWebSurvey", DbType="Bit NOT NULL")]
		public bool HasWebSurvey
		{
			get
			{
				return this._HasWebSurvey;
			}
			set
			{
				if ((this._HasWebSurvey != value))
				{
					this.OnHasWebSurveyChanging(value);
					this.SendPropertyChanging();
					this._HasWebSurvey = value;
					this.SendPropertyChanged("HasWebSurvey");
					this.OnHasWebSurveyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventType_CodeID", DbType="Int NOT NULL")]
		public int EventType_CodeID
		{
			get
			{
				return this._EventType_CodeID;
			}
			set
			{
				if ((this._EventType_CodeID != value))
				{
					this.OnEventType_CodeIDChanging(value);
					this.SendPropertyChanging();
					this._EventType_CodeID = value;
					this.SendPropertyChanged("EventType_CodeID");
					this.OnEventType_CodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookCaption", DbType="NVarChar(1000)")]
		public string FacebookCaption
		{
			get
			{
				return this._FacebookCaption;
			}
			set
			{
				if ((this._FacebookCaption != value))
				{
					this.OnFacebookCaptionChanging(value);
					this.SendPropertyChanging();
					this._FacebookCaption = value;
					this.SendPropertyChanged("FacebookCaption");
					this.OnFacebookCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterCaption", DbType="NVarChar(1000)")]
		public string TwitterCaption
		{
			get
			{
				return this._TwitterCaption;
			}
			set
			{
				if ((this._TwitterCaption != value))
				{
					this.OnTwitterCaptionChanging(value);
					this.SendPropertyChanging();
					this._TwitterCaption = value;
					this.SendPropertyChanged("TwitterCaption");
					this.OnTwitterCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintOption", DbType="Int NOT NULL")]
		public int PrintOption
		{
			get
			{
				return this._PrintOption;
			}
			set
			{
				if ((this._PrintOption != value))
				{
					this.OnPrintOptionChanging(value);
					this.SendPropertyChanging();
					this._PrintOption = value;
					this.SendPropertyChanged("PrintOption");
					this.OnPrintOptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PUEvent_PUConsumerData", Storage="_PUConsumerDatas", ThisKey="EventID", OtherKey="EventID")]
		public EntitySet<PUConsumerData> PUConsumerDatas
		{
			get
			{
				return this._PUConsumerDatas;
			}
			set
			{
				this._PUConsumerDatas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PUConsumerDatas(PUConsumerData entity)
		{
			this.SendPropertyChanging();
			entity.PUEvent = this;
		}
		
		private void detach_PUConsumerDatas(PUConsumerData entity)
		{
			this.SendPropertyChanging();
			entity.PUEvent = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PUTours")]
	public partial class PUTour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TourID;
		
		private int _ProgramID;
		
		private string _Name;
		
		private EntityRef<PUProgram> _PUProgram;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTourIDChanging(int value);
    partial void OnTourIDChanged();
    partial void OnProgramIDChanging(int value);
    partial void OnProgramIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public PUTour()
		{
			this._PUProgram = default(EntityRef<PUProgram>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TourID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TourID
		{
			get
			{
				return this._TourID;
			}
			set
			{
				if ((this._TourID != value))
				{
					this.OnTourIDChanging(value);
					this.SendPropertyChanging();
					this._TourID = value;
					this.SendPropertyChanged("TourID");
					this.OnTourIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					if (this._PUProgram.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProgramIDChanging(value);
					this.SendPropertyChanging();
					this._ProgramID = value;
					this.SendPropertyChanged("ProgramID");
					this.OnProgramIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PUProgram_PUTour", Storage="_PUProgram", ThisKey="ProgramID", OtherKey="ProgramID", IsForeignKey=true)]
		public PUProgram PUProgram
		{
			get
			{
				return this._PUProgram.Entity;
			}
			set
			{
				PUProgram previousValue = this._PUProgram.Entity;
				if (((previousValue != value) 
							|| (this._PUProgram.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PUProgram.Entity = null;
						previousValue.PUTours.Remove(this);
					}
					this._PUProgram.Entity = value;
					if ((value != null))
					{
						value.PUTours.Add(this);
						this._ProgramID = value.ProgramID;
					}
					else
					{
						this._ProgramID = default(int);
					}
					this.SendPropertyChanged("PUProgram");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PUPrograms")]
	public partial class PUProgram : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProgramID;
		
		private int _BrandID;
		
		private string _Name;
		
		private EntitySet<PUTour> _PUTours;
		
		private EntityRef<PUBrand> _PUBrand;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProgramIDChanging(int value);
    partial void OnProgramIDChanged();
    partial void OnBrandIDChanging(int value);
    partial void OnBrandIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public PUProgram()
		{
			this._PUTours = new EntitySet<PUTour>(new Action<PUTour>(this.attach_PUTours), new Action<PUTour>(this.detach_PUTours));
			this._PUBrand = default(EntityRef<PUBrand>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this.OnProgramIDChanging(value);
					this.SendPropertyChanging();
					this._ProgramID = value;
					this.SendPropertyChanged("ProgramID");
					this.OnProgramIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandID", DbType="Int NOT NULL")]
		public int BrandID
		{
			get
			{
				return this._BrandID;
			}
			set
			{
				if ((this._BrandID != value))
				{
					if (this._PUBrand.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBrandIDChanging(value);
					this.SendPropertyChanging();
					this._BrandID = value;
					this.SendPropertyChanged("BrandID");
					this.OnBrandIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PUProgram_PUTour", Storage="_PUTours", ThisKey="ProgramID", OtherKey="ProgramID")]
		public EntitySet<PUTour> PUTours
		{
			get
			{
				return this._PUTours;
			}
			set
			{
				this._PUTours.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PUBrand_PUProgram", Storage="_PUBrand", ThisKey="BrandID", OtherKey="BrandID", IsForeignKey=true)]
		public PUBrand PUBrand
		{
			get
			{
				return this._PUBrand.Entity;
			}
			set
			{
				PUBrand previousValue = this._PUBrand.Entity;
				if (((previousValue != value) 
							|| (this._PUBrand.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PUBrand.Entity = null;
						previousValue.PUPrograms.Remove(this);
					}
					this._PUBrand.Entity = value;
					if ((value != null))
					{
						value.PUPrograms.Add(this);
						this._BrandID = value.BrandID;
					}
					else
					{
						this._BrandID = default(int);
					}
					this.SendPropertyChanged("PUBrand");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PUTours(PUTour entity)
		{
			this.SendPropertyChanging();
			entity.PUProgram = this;
		}
		
		private void detach_PUTours(PUTour entity)
		{
			this.SendPropertyChanging();
			entity.PUProgram = null;
		}
	}
}
#pragma warning restore 1591
